'use client';

import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Footer } from '@/components/Footer';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f8f7f3] bg-grid flex flex-col">
      {/* Navigation */}
      <nav className="sticky top-0 left-0 right-0 z-50 bg-[#f8f7f3]/80 backdrop-blur-xl">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-[#8345dd] rounded-lg flex items-center justify-center">
              <Image src="/writine-light.svg" alt="Writine" width={20} height={20} />
            </div>
            <span className="font-semibold text-lg">Writine</span>
          </Link>
          <Button variant="ghost" size="sm" asChild>
            <Link href="/" className="gap-2">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Link>
          </Button>
        </div>
      </nav>

      {/* Content */}
      <main className="flex-1 max-w-3xl mx-auto px-6 py-16 w-full">
        <h1 className="text-4xl font-bold text-slate-900 mb-8">Terms of Service</h1>
        <p className="text-slate-500 mb-8">Last updated: December 23, 2025</p>

        <div className="prose prose-slate max-w-none">
          <h2>1. Agreement to Terms</h2>
          <p>
            By accessing or using Writine, you agree to be bound by these Terms of Service. If you disagree 
            with any part of the terms, you may not access the service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            Writine is an AI-powered blog writing and publishing platform that allows users to create, edit, 
            and publish blog content. Our service includes AI content generation, SEO optimization tools, 
            and custom domain publishing.
          </p>

          <h2>3. User Accounts</h2>
          <p>When you create an account, you must:</p>
          <ul>
            <li>Provide accurate and complete information</li>
            <li>Maintain the security of your account credentials</li>
            <li>Promptly update any information that changes</li>
            <li>Accept responsibility for all activities under your account</li>
          </ul>

          <h2>4. Acceptable Use</h2>
          <p>You agree not to use Writine to:</p>
          <ul>
            <li>Violate any applicable laws or regulations</li>
            <li>Infringe on intellectual property rights of others</li>
            <li>Publish harmful, offensive, or misleading content</li>
            <li>Distribute malware or engage in phishing</li>
            <li>Attempt to gain unauthorized access to our systems</li>
            <li>Use the service for spam or bulk messaging</li>
          </ul>

          <h2>5. Content Ownership</h2>
          <p>
            You retain ownership of all content you create using Writine. By using our service, you grant us 
            a limited license to host, display, and distribute your content as necessary to provide the service.
          </p>

          <h2>6. AI-Generated Content</h2>
          <p>
            Content generated by our AI tools is provided &quot;as is.&quot; You are responsible for reviewing, 
            editing, and ensuring the accuracy of AI-generated content before publishing. We do not guarantee 
            that AI-generated content is free from errors or suitable for any particular purpose.
          </p>

          <h2>7. Subscription and Payments</h2>
          <p>
            Some features require a paid subscription. By subscribing, you agree to pay the applicable fees. 
            Subscriptions automatically renew unless cancelled before the renewal date. Refunds are handled 
            according to our refund policy.
          </p>

          <h2>8. Free Trial</h2>
          <p>
            We offer a 7-day free trial for new users. You must provide payment information to start the trial. 
            If you don&apos;t cancel before the trial ends, you will be charged for the subscription.
          </p>

          <h2>9. Termination</h2>
          <p>
            We may terminate or suspend your account immediately, without prior notice, for conduct that we 
            believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason.
          </p>

          <h2>10. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Writine shall not be liable for any indirect, incidental, 
            special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred 
            directly or indirectly.
          </p>

          <h2>11. Disclaimer of Warranties</h2>
          <p>
            The service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, 
            either express or implied, including but not limited to implied warranties of merchantability, 
            fitness for a particular purpose, or non-infringement.
          </p>

          <h2>12. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. We will provide notice of significant changes 
            by posting the new Terms on this page. Your continued use of the service after changes constitutes 
            acceptance of the new terms.
          </p>

          <h2>13. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the jurisdiction 
            in which we operate, without regard to its conflict of law provisions.
          </p>

          <h2>14. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please{' '}
            <Link href="/contact" className="text-[#8345dd] hover:underline">
              contact us
            </Link>
            .
          </p>
        </div>
      </main>

      <Footer />
    </div>
  );
}
